/*
 * ba_builtin_schemas.h - the 11 builtin tool schemas, compiled in.
 *
 * Builtin division: meta-operations on the agent's own state space,
 * plus the execution anchor and content-transfers that need C logic.
 * Names deliberately match mainstream-agent training vocabulary.
 * The dynamic zone (tools.json) only carries "world-operation sugar"
 * (ls/head/tail/wc/stat...); entries must not shadow these names.
 *
 * Copyright (C) 2026 by Lloyd Zhou <lloydzhou@qq.com>
 *
 * Licensed under GPLv2, see file LICENSE in this source tree.
 */
#ifndef BA_BUILTIN_SCHEMAS_H
#define BA_BUILTIN_SCHEMAS_H

static const char ba_builtin_schemas[] =
"[\n"
"  {\n"
"    \"name\": \"Read\",\n"
"    \"description\": \"Read a file. Output includes line numbers (cat -n format). By default reads the whole file; use offset/limit to read specific line ranges. IMPORTANT - Prefer Grep over Read when searching for content.\",\n"
"    \"input_schema\": { \"type\": \"object\",\n"
"      \"properties\": { \"path\": { \"type\": \"string\", \"description\": \"Path to read\" },\n"
"                      \"offset\": { \"type\": \"integer\", \"description\": \"Start line (1-indexed)\" },\n"
"                      \"limit\": { \"type\": \"integer\", \"description\": \"Number of lines to read\" } },\n"
"      \"required\": [\"path\"] }\n"
"  },\n"
"  {\n"
"    \"name\": \"Write\",\n"
"    \"description\": \"Write a file to the local filesystem.\",\n"
"    \"input_schema\": { \"type\": \"object\",\n"
"      \"properties\": { \"path\": { \"type\": \"string\", \"description\": \"Path to write\" },\n"
"                      \"content\": { \"type\": \"string\", \"description\": \"Content to write\" } },\n"
"      \"required\": [\"path\", \"content\"] }\n"
"  },\n"
"  {\n"
"    \"name\": \"Edit\",\n"
"    \"description\": \"Replace an exact string in a file. old_string must match byte-for-byte (including whitespace/indent/newlines) and must occur exactly once. Copy the exact text before calling Edit.\",\n"
"    \"input_schema\": { \"type\": \"object\",\n"
"      \"properties\": { \"path\": { \"type\": \"string\", \"description\": \"Path to edit\" },\n"
"                      \"old_string\": { \"type\": \"string\", \"description\": \"Exact text to replace (must be unique)\" },\n"
"                      \"new_string\": { \"type\": \"string\", \"description\": \"Replacement text\" } },\n"
"      \"required\": [\"path\", \"old_string\", \"new_string\"] }\n"
"  },\n"
"  {\n"
"    \"name\": \"Bash\",\n"
"    \"description\": \"Execute a shell command on busybox sh: pipelines, redirection, loops are all available; the command set is whatever this busybox binary provides (cat, grep, sed, find, ...). Returns stdout+stderr, truncated at 128KB.\",\n"
"    \"input_schema\": { \"type\": \"object\",\n"
"      \"properties\": { \"command\": { \"type\": \"string\", \"description\": \"The shell command to execute\" },\n"
"                      \"timeout_ms\": { \"type\": \"integer\", \"description\": \"Timeout ms (default 120000)\" } },\n"
"      \"required\": [\"command\"] }\n"
"  },\n"
"  {\n"
"    \"name\": \"Glob\",\n"
"    \"description\": \"Find files matching a single glob pattern. Use multiple Glob calls if you need multiple patterns.\",\n"
"    \"input_schema\": { \"type\": \"object\",\n"
"      \"properties\": { \"pattern\": { \"type\": \"string\", \"description\": \"Glob pattern, e.g. **/*.sh\" },\n"
"                      \"path\": { \"type\": \"string\", \"description\": \"Directory to search from (default .)\" } },\n"
"      \"required\": [\"pattern\"] }\n"
"  },\n"
"  {\n"
"    \"name\": \"Grep\",\n"
"    \"description\": \"Search file contents with a regular expression (busybox grep). Use context to show surrounding lines - often enough for Edit without a separate Read.\",\n"
"    \"input_schema\": { \"type\": \"object\",\n"
"      \"properties\": { \"pattern\": { \"type\": \"string\", \"description\": \"Regular expression\" },\n"
"                      \"path\": { \"type\": \"string\", \"description\": \"File or directory to search in (default ., recursive)\" },\n"
"                      \"context\": { \"type\": \"integer\", \"description\": \"Lines of context before and after each match\" } },\n"
"      \"required\": [\"pattern\"] }\n"
"  },\n"
"  {\n"
"    \"name\": \"TodoWrite\",\n"
"    \"description\": \"Create and manage a structured task list for the current session. Use proactively for complex multi-step work. Send the complete list each time, not a partial diff. The rendered list is returned as this call's result and lives in conversation history.\",\n"
"    \"input_schema\": { \"type\": \"object\",\n"
"      \"properties\": { \"todos\": { \"type\": \"array\",\n"
"          \"items\": { \"type\": \"object\",\n"
"            \"properties\": { \"content\": { \"type\": \"string\", \"description\": \"Short, actionable task\" },\n"
"                            \"status\": { \"type\": \"string\", \"description\": \"pending, in_progress, or completed\" } },\n"
"            \"required\": [\"content\", \"status\"] } } },\n"
"      \"required\": [\"todos\"] }\n"
"  },\n"
"  {\n"
"    \"name\": \"PlanConfirm\",\n"
"    \"description\": \"Confirm and lock in the current plan draft (plan.draft becomes plan.md and is included in every subsequent request). Call ONLY when the user explicitly confirms.\",\n"
"    \"input_schema\": { \"type\": \"object\", \"properties\": {} }\n"
"  },\n"
"  {\n"
"    \"name\": \"PlanClear\",\n"
"    \"description\": \"Clear the current plan. Call when the plan is fully completed and all tasks are done.\",\n"
"    \"input_schema\": { \"type\": \"object\", \"properties\": {} }\n"
"  },\n"
"  {\n"
"    \"name\": \"Skill\",\n"
"    \"description\": \"Load a skill (prompt/playbook stored as skills/<name>/SKILL.md under cwd, ~/.agents or $BB_AGENT_HOME) into this conversation. Its content becomes part of your instructions; follow it.\",\n"
"    \"input_schema\": { \"type\": \"object\",\n"
"      \"properties\": { \"name\": { \"type\": \"string\", \"description\": \"Skill name\" } },\n"
"      \"required\": [\"name\"] }\n"
"  },\n"
"  {\n"
"    \"name\": \"SubAgent\",\n"
"    \"description\": \"Run a fresh busyagent session on a self-contained prompt and return its final answer. Use for isolated sub-tasks that deserve their own context.\",\n"
"    \"input_schema\": { \"type\": \"object\",\n"
"      \"properties\": { \"prompt\": { \"type\": \"string\", \"description\": \"Complete, self-contained task description\" },\n"
"                      \"description\": { \"type\": \"string\", \"description\": \"Short task summary\" } },\n"
"      \"required\": [\"prompt\"] }\n"
"  }\n"
"]\n";

#endif /* BA_BUILTIN_SCHEMAS_H */
