# Makefile for busybox
#
# Copyright (C) 2026 by Lloyd Zhou <lloydzhou@qq.com>
#
# Licensed under GPLv2, see file LICENSE in this source tree.

lib-y:=

# busybox's kbuild (scripts/Makefile.lib) has no ccflags-y; per-object
# flags via CFLAGS_<file>.o are the supported extension point
# (-D_GNU_SOURCE and -std=gnu99 already come from Makefile.flags).
CFLAGS_ba_impl.o = -Wno-declaration-after-statement
CFLAGS_busyagent.o = -Wno-declaration-after-statement

INSERT
