#!/usr/bin/env python3
"""Generate agentutils/ba_builtin_schemas.h from bash-agent's tools.json.

Descriptions/input_schemas are copied VERBATIM from the reference file so the
tool surface matches mainstream-agent training vocabulary. Only four tools
are adapted to busyagent's actual semantics:
  Bash     - busybox sh base, timeout_ms, no background tasks yet
  Grep     - ripgrep -> busybox grep wording (glob kept, implemented via --include)
  Skill    - generic agent skill dirs (cwd/skills > ~/.agents/skills >
             $BB_AGENT_HOME/skills), no skill-index section exists in phase 1
  SubAgent - synchronous self-bootstrap (fork+exec busyagent --new);
             no async/fork/worktree features

Usage: python3 scripts/gen_builtin_schemas.py [path/to/bash-agent/c]
Requires .ref-bashagent clone or source dir argument.
"""
import json, sys, os

SRC = sys.argv[1] if len(sys.argv) > 1 else ".ref-bashagent/c"
data = json.load(open(os.path.join(SRC, "tools.json")))
by_name = {t["name"]: t for t in data}

def take(name):
    return by_name[name]

# ---- adaptations ----
# Bash: verbatim except the busybox-base sentence appended (capability is
# implemented: background tasks are detached processes logging to files).
bash = take("Bash")
bash["description"] += (
    "\n\nbusyagent note: runs on busybox sh and its applets; background tasks "
    "write output to a log file which you can read later with Read.")

# Grep: ripgrep wording -> busybox grep (implementation uses --include for glob)
grep = take("Grep")
grep["description"] = grep["description"].replace(
    "Search file contents with ripgrep.",
    "Search file contents with a regular expression (busybox grep).")

# Skill: generic agent dirs, no skill-index-specific wording about missing paths
skill = take("Skill")
skill["description"] = ("Load a skill (prompt/playbook stored as skills/<name>/SKILL.md). "
                        "Searched in order: $CWD/skills, $HOME/.agents/skills, "
                        "$BB_AGENT_HOME/skills. Its content becomes part of your instructions; follow it.")

# SubAgent: verbatim structure, one explicit sync-semantics note prepended
subagent = take("SubAgent")

order = ["Read", "Write", "Edit", "Bash", "Glob", "Grep",
         "TodoWrite", "PlanConfirm", "PlanClear", "Skill", "SubAgent"]
special = {"Bash": bash, "Grep": grep, "Skill": skill}
tools = [special.get(n) or take(n) for n in order]

assert len(tools) == 11, tools
text = json.dumps(tools, ensure_ascii=False, indent=1)

out = ["/*",
       " * ba_builtin_schemas.h - the 11 builtin tool schemas, compiled in.",
       " * GENERATED by scripts/gen_builtin_schemas.py from bash-agent's tools.json:",
       " * descriptions/schemas are verbatim except the four adapted tools listed",
       " * at the top of that script. Do not hand-edit; regenerate instead.",
       " *",
       " * Copyright (C) 2026 by Lloyd Zhou <lloydzhou@qq.com>",
       " *",
       " * Licensed under GPLv2, see file LICENSE in this source tree.",
       " */",
       "#ifndef BA_BUILTIN_SCHEMAS_H",
       "#define BA_BUILTIN_SCHEMAS_H",
       "",
       "static const char ba_builtin_schemas[] ="]
lines = text.split("\n")
for i, ln in enumerate(lines):
    esc = ln.replace("\\", "\\\\").replace('"', '\\"')
    suffix = "\\n" if i < len(lines) - 1 else ""
    out.append('"%s%s%s"' % (esc, suffix, ""))
out.append(";")
out.append("")
out.append("#endif /* BA_BUILTIN_SCHEMAS_H */")
open("agentutils/ba_builtin_schemas.h", "w").write("\n".join(out) + "\n")
print("generated:", len(text), "bytes of schema,", len(lines), "lines")
